### ISSUE TITLE
Fix list of article links formatting

### ISSUE THREAD

**Issue by ghost** [Mobilization/2017.mobilization.pl#5] opened 2017-09-06 17:40 UTC
Hi,

it seems to be unfinished description of Jorge Castillo:

<a href="http://pl.tinypic.com?ref=jkax77" target="_blank"><img src="http://i68.tinypic.com/jkax77.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Was that intentional or something went wrong?

If you mind, I can create MR with fixed code. Just let me know.

Cheers!

**Comment by marekdef** [comment] 2017-09-06 18:43
Hi Piotr,

Many thanks for your cooperation.

The problem is always time :) - so we did not have time to spot it.
@mariopce wrote some piece of script to synchronize but apparently, we forgot to check all the cases :).


If you don't mind please create PR with fixed MR.

@marciniwanicki do we support MR in that field?

**Comment by marciniwanicki** [comment] 2017-09-07 07:36
Hi @piotrek1543,

thank you for your time and great contribution! As you noticed we're not web dev/QA ninjas :) PR would be great! Once your request is accepted and merged, I will regenerate the website. Please just let me know if you plan to submit PR, if not, I will fix that myself. 

@marekdef PR is ok, as far I am concerned MR == PR in GitLab terminology.

**Closed as completed** 2017-11-15 09:11 UTC
Labels: bug
